### ISSUE TITLE
Modules support

### ISSUE THREAD

**Issue by aij** [sbt/sbt-appengine#30]
Are there plans to support modules? https://developers.google.com/appengine/docs/java/modules/

I'm not sure whether they could be indirectly supported via subprojects or something, but if that is the way to go, it would be nice to have an example of best practice.

I haven't had a chance to experiment with modules at all yet, but I was hoping someone might know more about them since backends are being deprecated in favor of modules.

**Comment by eed3si9n** [comment]
PR would be welcomed, but I probably won't do it myself since I don't use appengine.

**Comment by xuwei-k** [comment]
https://cloud.google.com/appengine/docs/standard/java/an-overview-of-app-engine

> Note: Services were previously called "modules", and services are still declared in app.yaml files as modules. Example: module: service_name .
