### ISSUE TITLE
Not Java 8 compatible 

### ISSUE THREAD

**Issue by AIMMOTH** [sbt/sbt-appengine#35]
Running appengineDevServer

> appengineDevServer
[info] Compiling 3 Scala sources to C:\dev\scala\source\sbt-appengine\temp\simpl
e\target\scala-2.9.2\classes...
[error] error while loading CharSequence, class file 'C:\Program Files\Java\jdk1
.8.0_60\jre\lib\rt.jar(java/lang/CharSequence.class)' is broken
[error] (bad constant pool tag 15 at byte 1501)
[error] error while loading AnnotatedElement, class file 'C:\Program Files\Java\
jdk1.8.0_60\jre\lib\rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[error] (bad constant pool tag 15 at byte 2713)
[error] two errors found
[error] (compile:compile) Compilation failed
[error] Total time: 2 s, completed 2015-sep-10 19:51:43

**Comment by eed3si9n** [comment]
Scala 2.9.x cannot be compiled with JDK 1.8. This is a known limitation of Scala, not sbt-appengine.

**Comment by AIMMOTH** [comment]
Ok, thanks
