### ISSUE TITLE
Cannot specify additional javaOptions for dev app server

### ISSUE THREAD

**Issue by akochnev** [sbt/sbt-appengine#36]
I needed to add an option (-D--enable_all_permissions=true") to the options with which the java dev app server is started with. Unfortunately, in the current configuration, the javaOptions passed to the dev app server are overwritten and my project configuration is not considered. For example, when I add : 

```
// in gae.devServer
javaOptions  := Seq(
  "-Dtapestry.execution-mode=DevelopmentMode",
  "-Dappengine.fullscan.seconds=-1",
  "-D--enable_all_permissions=true",
  "-Dappengine.generated.dir=" + baseDirectory.value + "/appengine-generated"
)
```

These options are never passed to the dev app server

**Comment by breilly2** [comment]
I found this to work:
```
javaOptions in appengineDevServer in Compile ++= Seq(
  "-Duse_jetty9_runtime=true",
  "-D--enable_all_permissions=true")
```
(note the addition of `in Compile`)

Incidentally, you'll need to add `-Duse_jetty9_runtime=true` when moving from app engine SDK 1.9.63 to 1.9.64.
